### Ik wil een lijst van de te veilen producten of diensten
GET http://localhost:3000/Auctions
Content-Type: application/json

> {%
client.test("Retrieve auction list",
function() {
	client.assert(response.body.length !==0 , "Auction list is 0");

}
);
%}